name: Test React App Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Cache Yarn dependencies
      uses: actions/cache@v2
      with:
        path: react/node_modules
        key: ${{ runner.OS }}-yarn-${{ hashFiles('react/yarn.lock') }}

    - name: Install dependencies
      run: |
        cd react
        yarn install

    - name: Build React App
      run: |
        cd react
        CI=false yarn build
    
